SKILL_TAXONOMY = {

    "programming": {
        "assembly": ["assembly","Assembly","asm","assembly language","low level programming"],
        "bash": ["bash","Bash","bash scripting","shell bash"],
        "c": ["c","C","c language","ansi c"],
        "c++": ["c++","C++","cpp","c plus plus","cplusplus"],
        "c#": ["c#","C#","c sharp","csharp",".net c#"],
        "dart": ["dart","Dart","dart language","flutter dart"],
        "go": ["go","Go","golang","GoLang"],
        "groovy": ["groovy","Groovy","groovy language"],
        "java": ["java","Java","java se","java ee","jdk","jre"],
        "javascript": ["javascript","JavaScript","js","JS","ecmascript","es"],
        "kotlin": ["kotlin","Kotlin","kotlin language"],
        "lua": ["lua","Lua","lua scripting"],
        "matlab": ["matlab","MATLAB","matrix laboratory"],
        "perl": ["perl","Perl","perl scripting"],
        "php": ["php","PHP","php language","php scripting"],
        "powershell": ["powershell","PowerShell","ps","windows powershell"],
        "python": ["python","Python","python3","python 3","cpython","py"],
        "r": ["r","R","r programming","r language","r stats"],
        "ruby": ["ruby","Ruby","ruby language","ruby programming"],
        "rust": ["rust","Rust","rustlang"],
        "scala": ["scala","Scala","scala language"],
        "shell": ["shell","Shell","shell scripting","sh scripting"],
        "swift": ["swift","Swift","swift language","apple swift"],
        "typescript": ["typescript","TypeScript","ts","TS","typed javascript"]
    },
    
    "web": {
        "angular": ["angular","Angular","angularjs","AngularJS","angular framework"],
        "aspnet": ["asp.net","ASP.NET","aspnet","asp.net core","ASP.NET Core",".net web"],
        "css": ["css","Css","CSS","css3","CSS3","cascading style sheets"],
        "django": ["django","Django","django framework","django web framework"],
        "express": ["express","Express","expressjs","ExpressJS","express framework"],
        "flask": ["flask","Flask","flask framework","python flask"],
        "graphql": ["graphql","GraphQL","graphql api"],
        "html": ["html","Html","HTML","html5","HTML5","hypertext markup language"],
        "jwt": ["jwt","JWT","json web token"],
        "node": ["node","Node","nodejs","NodeJS","node.js","javascript runtime"],
        "oauth": ["oauth","OAuth","oauth2","oauth 2.0"],
        "react": ["react","React","reactjs","ReactJS","react.js","react framework"],
        "rest": ["rest","REST","rest api","restful services"],
        "spring": ["spring","Spring","spring framework","spring boot","Spring Boot"],
        "vue": ["vue","Vue","vuejs","VueJS","vue.js","vue framework"],
        "websocket": ["websocket","WebSocket","web sockets"]
    },
    
    "databases": {
        "cassandra": ["cassandra","Cassandra","apache cassandra","cassandra db"],
        "mariadb": ["mariadb","MariaDB","maria db"],
        "mongodb": ["mongodb","MongoDB","mongo","mongo db","mongodb atlas"],
        "mysql": ["mysql","MySQL","my sql","mysql database"],
        "nosql": ["nosql","NoSQL","no sql","non relational","non relational database"],
        "oracle": ["oracle","Oracle","oracle db","oracle database","oracle rdbms"],
        "postgresql": ["postgresql","PostgreSQL","postgres","postgre sql","pgsql","psql"],
        "redis": ["redis","Redis","redis db","in memory redis"],
        "sqlite": ["sqlite","SQLite","sql lite","embedded sqlite"],
        "sql": ["sql","SQL","structured query language","relational sql"]
    },

    "cloud": {
        "aws": ["aws","AWS","amazon web services","amazon aws","aws cloud"],
        "azure": ["azure","Azure","microsoft azure","azure cloud"],
        "cloud_computing": ["cloud","cloud computing","cloud technology","cloud infrastructure"],
        "gcp": ["gcp","GCP","google cloud","google cloud platform","gcloud"],
        "iam": ["iam","IAM","identity and access management"],
        "serverless": ["serverless","serverless computing","faas","function as a service"],
        "virtualization": ["virtualization","virtual machines","vm","hypervisor"]
    },
    
    "devops": {
        "ansible": ["ansible","Ansible","ansible automation","ansible playbook"],
        "ci_cd": ["ci/cd","CI/CD","continuous integration","continuous delivery","continuous deployment"],
        "docker": ["docker","Docker","docker containers","docker engine"],
        "git": ["git","Git","git scm","version control"],
        "github": ["github","GitHub","github repositories","github actions"],
        "gitlab": ["gitlab","GitLab","gitlab ci","gitlab pipeline"],
        "helm": ["helm","Helm","helm charts"],
        "jenkins": ["jenkins","Jenkins","jenkins ci","jenkins pipeline"],
        "kubernetes": ["kubernetes","Kubernetes","k8s","container orchestration"],
        "terraform": ["terraform","Terraform","infrastructure as code","iac terraform"]
    },
    
    "operating_systems": {
        "active_directory": ["active directory","Active Directory","ad","windows ad","directory services"],
        "boot_process": ["boot process","system boot","boot sequence"],
        "command_line": ["command line","cli","terminal","shell"],
        "cron_jobs": ["cron","cron jobs","task scheduling linux"],
        "disk_management": ["disk management","disk partitioning","mounting","file systems"],
        "file_permissions": ["file permissions","chmod","chown","access permissions"],
        "group_policy": ["group policy","gpo","group policy objects"],
        "kernel_management": ["kernel","kernel management","kernel tuning"],
        "linux": ["linux","Linux","ubuntu","debian","centos","red hat","rhel","fedora"],
        "log_management": ["log management","system logs","event logs"],
        "macos": ["macos","MacOS","mac os","osx","OS X","apple macos"],
        "package_management": ["package management","apt","yum","dnf","brew"],
        "patch_management": ["patch management","system patching","os updates"],
        "power_management": ["power management","sleep modes","hibernate"],
        "process_management": ["process management","process monitoring","task management"],
        "remote_access": ["remote access","ssh","remote desktop","rdp"],
        "resource_monitoring": ["resource monitoring","cpu usage","memory usage","disk usage"],
        "security_hardening": ["os hardening","security hardening","system hardening"],
        "service_management": ["service management","system services","systemctl"],
        "shell_scripting": ["shell scripting","bash scripting","os scripting"],
        "startup_services": ["startup services","boot services","init services"],
        "system_backup": ["system backup","os backup","system restore"],
        "system_configuration": ["system configuration","os configuration"],
        "system_installation": ["os installation","operating system installation"],
        "system_performance": ["system performance","performance tuning","system optimization"],
        "system_troubleshooting": ["system troubleshooting","os troubleshooting"],
        "task_scheduler": ["task scheduler","windows task scheduler"],
        "unix": ["unix","Unix","aix","solaris","hp ux"],
        "user_management": ["user management","account management","user accounts"],
        "virtualization_support": ["virtualization support","vm support","hypervisor support"],
        "windows": ["windows","Windows","microsoft windows"],
        "windows_registry": ["windows registry","registry editor","regedit"],
        "windows_server": ["windows server","Windows Server","windows server 2016","windows server 2019","windows server 2022"]
    },
    
    "networking": {
        "dhcp": ["dhcp","DHCP","dynamic host configuration protocol"],
        "dns": ["dns","DNS","domain name system"],
        "firewall": ["firewall","Firewall","network firewall"],
        "lan": ["lan","LAN","local area network"],
        "nat": ["nat","NAT","network address translation"],
        "routing": ["routing","router","ip routing"],
        "switching": ["switching","network switching","lan switching"],
        "tcp_ip": ["tcp/ip","TCP/IP","internet protocol suite"],
        "vpn": ["vpn","VPN","virtual private network"],
        "wan": ["wan","WAN","wide area network"]
    },
    
    "security": {
        "authentication": ["authentication","auth","user authentication"],
        "authorization": ["authorization","access control","rbac"],
        "cybersecurity": ["cybersecurity","cyber security","information security","infosec"],
        "encryption": ["encryption","cryptography","data encryption"],
        "ethical_hacking": ["ethical hacking","white hat hacking","whitehat"],
        "penetration_testing": ["penetration testing","pentesting","pen test"],
        "siem": ["siem","SIEM","security information and event management"]
    },

    "data": {
        "data_analysis": ["data analysis","data analytics"],
        "data_science": ["data science","data scientist"],
        "deep_learning": ["deep learning","dl","neural networks"],
        "machine_learning": ["machine learning","ml","predictive modeling"],
        "nlp": ["nlp","natural language processing"],
        "numpy": ["numpy","NumPy","python numpy"],
        "pandas": ["pandas","Pandas","python pandas"],
        "pytorch": ["pytorch","PyTorch","torch"],
        "tensorflow": ["tensorflow","TensorFlow","tf"]
    },

    "mobile": {
        "android": ["android","Android","android development"],
        "flutter": ["flutter","Flutter","dart flutter"],
        "ios": ["ios","iOS","apple ios"],
        "react_native": ["react native","React Native","react-native"]
    },
    
    "tools": {
        "excel": ["excel","Excel","microsoft excel"],
        "figma": ["figma","Figma","figma design"],
        "illustrator": ["illustrator","Illustrator","adobe illustrator"],
        "jira": ["jira","Jira","atlassian jira"],
        "photoshop": ["photoshop","Photoshop","adobe photoshop"],
        "powerbi": ["power bi","Power BI","microsoft power bi"],
        "postman": ["postman","Postman","api testing tool"],
        "tableau": ["tableau","Tableau","tableau bi"],
        "vscode": ["vscode","VS Code","visual studio code"]
    },
    
    "it_support": {
        "active_directory": ["active directory","Active Directory","ad"],
        "hardware_support": ["hardware support","hardware troubleshooting","desktop support"],
        "helpdesk": ["helpdesk","help desk","service desk"],
        "os_installation": ["os installation","operating system installation"],
        "patch_management": ["patch management","system patching"],
        "remote_support": ["remote support","remote troubleshooting"],
        "technical_support": ["technical support","it support","tech support"],
        "troubleshooting": ["troubleshooting","issue resolution","problem solving"]
    },

    "cyber_security": {
        "access_control": ["access control","authorization","rbac","role based access control"],
        "active_defense": ["active defense","defensive security"],
        "adversary_simulation": ["adversary simulation","attack simulation","red team simulation"],
        "antivirus": ["antivirus","anti virus","endpoint antivirus"],
        "application_security": ["application security","appsec","secure application development"],
        "authentication": ["authentication","auth","user authentication"],
        "authorization": ["authorization","access authorization"],
        "blue_team": ["blue team","defensive team","security operations team"],
        "brute_force": ["brute force","brute force attack","password brute force"],
        "bug_bounty": ["bug bounty","bug bounty hunting","vulnerability bounty"],
        "cloud_security": ["cloud security","aws security","azure security","gcp security"],
        "computer_forensics": ["computer forensics","digital forensics","cyber forensics"],
        "cryptography": ["cryptography","encryption","data encryption"],
        "csirt": ["csirt","computer security incident response team"],
        "cybersecurity": ["cybersecurity","cyber security","information security","infosec"],
        "ddos": ["ddos","distributed denial of service","dos attack"],
        "digital_forensics": ["digital forensics","forensic analysis","forensic investigation"],
        "endpoint_security": ["endpoint security","endpoint protection","edr"],
        "ethical_hacking": ["ethical hacking","ethical hacker","white hat hacking","whitehat"],
        "exploit_development": ["exploit development","exploit writing"],
        "firewall": ["firewall","network firewall","security firewall"],
        "governance_risk_compliance": ["grc","governance risk compliance","security governance"],
        "hashing": ["hashing","password hashing","hash algorithms"],
        "ids": ["ids","intrusion detection system"],
        "incident_response": ["incident response","security incident response","ir"],
        "information_security": ["information security","infosec"],
        "insider_threat": ["insider threat","internal threat"],
        "intrusion_detection": ["intrusion detection","ids"],
        "intrusion_prevention": ["ips","intrusion prevention system"],
        "key_management": ["key management","encryption key management"],
        "log_analysis": ["log analysis","security log analysis"],
        "malware_analysis": ["malware analysis","malware reverse engineering"],
        "man_in_the_middle": ["mitm","man in the middle","man-in-the-middle attack"],
        "network_security": ["network security","network protection"],
        "osint": ["osint","open source intelligence"],
        "password_cracking": ["password cracking","credential cracking"],
        "penetration_testing": ["penetration testing","pentesting","pen test","pentest"],
        "phishing": ["phishing","phishing attack","email phishing"],
        "privilege_escalation": ["privilege escalation","privesc"],
        "purple_team": ["purple team","red blue collaboration"],
        "red_team": ["red team","offensive security team"],
        "reverse_engineering": ["reverse engineering","binary analysis"],
        "risk_assessment": ["risk assessment","security risk analysis"],
        "security_audit": ["security audit","security assessment"],
        "security_awareness": ["security awareness","user awareness training"],
        "security_monitoring": ["security monitoring","continuous monitoring"],
        "security_operations": ["security operations","soc operations"],
        "siem": ["siem","security information and event management"],
        "social_engineering": ["social engineering","human hacking"],
        "soc": ["soc","security operations center"],
        "ssl_tls": ["ssl","tls","ssl tls","secure sockets layer","transport layer security"],
        "threat_hunting": ["threat hunting","proactive threat hunting"],
        "threat_intelligence": ["threat intelligence","cyber threat intelligence","cti"],
        "two_factor_authentication": ["2fa","two factor authentication","multi factor authentication"],
        "vulnerability_assessment": ["vulnerability assessment","va","vulnerability scanning"],
        "vulnerability_management": ["vulnerability management","patch management security"],
        "web_security": ["web security","web application security"],
        "wireless_security": ["wireless security","wifi security"]
    },
    "operations": {
        "incident_management": ["incident management","incident handling"],
        "on_call_support": ["on call support","on-call rotation"],
        "sla_management": ["sla","service level agreement"],
        "ticket_management": ["ticket management","ticketing systems"],
        "vendor_coordination": ["vendor coordination","third party support"]
    },
    "problem_solving": {
        "analytical_thinking": ["analytical thinking","analysis skills","analytical problem solving"],
        "critical_thinking": ["critical thinking","logical thinking","reasoning skills"],
        "debugging": ["debugging","bug fixing","issue debugging","root bug analysis"],
        "decision_making": ["decision making","technical decision making"],
        "fault_isolation": ["fault isolation","issue isolation","problem isolation"],
        "hypothesis_testing": ["hypothesis testing","test assumptions","validate assumptions"],
        "incident_analysis": ["incident analysis","incident investigation"],
        "log_analysis": ["log analysis","analyzing logs","system log analysis"],
        "pattern_recognition": ["pattern recognition","issue pattern detection"],
        "performance_analysis": ["performance analysis","bottleneck analysis","performance troubleshooting"],
        "problem_decomposition": ["problem decomposition","breaking down problems","divide and solve"],
        "process_optimization": ["process optimization","workflow optimization","efficiency improvement"],
        "root_cause_analysis": ["root cause analysis","rca","cause analysis"],
        "systematic_troubleshooting": ["systematic troubleshooting","structured troubleshooting"],
        "technical_troubleshooting": ["technical troubleshooting","issue resolution","problem resolution"],
        "time_management": ["time management","priority management"],
        "tradeoff_analysis": ["tradeoff analysis","cost benefit analysis","risk tradeoff"],
        "workflow_improvement": ["workflow improvement","process improvement"]
    },

    "communication_skills": {
        "active_listening": ["active listening","attentive listening","listening skills"],
        "client_communication": ["client communication","customer communication","stakeholder communication"],
        "cross_team_communication": ["cross team communication","inter team communication","cross functional communication"],
        "documentation_writing": ["documentation writing","technical documentation","process documentation"],
        "email_communication": ["email communication","professional email writing"],
        "incident_communication": ["incident communication","outage communication","status updates"],
        "knowledge_transfer": ["knowledge transfer","kt","handover communication"],
        "meeting_facilitation": ["meeting facilitation","meeting coordination"],
        "presentation_skills": ["presentation skills","technical presentations","demo presentations"],
        "report_writing": ["report writing","technical reports","status reports"],
        "requirement_gathering": ["requirement gathering","requirements analysis","needs analysis"],
        "stakeholder_management": ["stakeholder management","stakeholder communication"],
        "technical_explanation": ["technical explanation","explaining technical concepts","technical communication"],
        "team_communication": ["team communication","internal communication"],
        "verbal_communication": ["verbal communication","spoken communication"],
        "written_communication": ["written communication","written skills","professional writing"]
    },
    "corporate_skills": {
        "accountability": ["accountability","ownership","responsibility"],
        "adaptability": ["adaptability","adaptable","flexibility","change adaptation"],
        "attention_to_detail": ["attention to detail","detail oriented","accuracy"],
        "business_awareness": ["business awareness","business understanding","commercial awareness"],
        "collaboration": ["collaboration","team collaboration","working collaboratively"],
        "communication": ["communication","professional communication","workplace communication"],
        "conflict_resolution": ["conflict resolution","conflict management","issue mediation"],
        "continuous_improvement": ["continuous improvement","process improvement","kaizen mindset"],
        "customer_focus": ["customer focus","customer centricity","client focus"],
        "decision_making": ["decision making","decision ownership","sound judgment"],
        "documentation": ["documentation","process documentation","technical documentation"],
        "email_etiquette": ["email etiquette","professional emailing","email communication"],
        "emotional_intelligence": ["emotional intelligence","empathy","emotional awareness"],
        "ethics": ["professional ethics","ethical behavior","integrity"],
        "feedback_handling": ["feedback handling","receiving feedback","constructive feedback"],
        "follow_up": ["follow up","task follow-up","closure mindset"],
        "initiative": ["initiative","self starter","proactiveness"],
        "learning_agility": ["learning agility","continuous learning","upskilling"],
        "meeting_management": ["meeting management","meeting discipline","meeting facilitation"],
        "multitasking": ["multitasking","task switching","handling multiple tasks"],
        "negotiation": ["negotiation","professional negotiation","stakeholder negotiation"],
        "organizational_skills": ["organizational skills","organization skills","work organization"],
        "prioritization": ["prioritization","task prioritization","priority management"],
        "problem_solving": ["problem solving","issue resolution","analytical problem solving"],
        "professionalism": ["professionalism","professional conduct","workplace behavior"],
        "project_coordination": ["project coordination","project handling","delivery coordination"],
        "remote_working": ["remote working","remote collaboration","distributed work"],
        "requirements_understanding": ["requirements understanding","requirement analysis","needs analysis"],
        "risk_awareness": ["risk awareness","risk identification","risk management"],
        "stakeholder_management": ["stakeholder management","stakeholder communication","stakeholder alignment"],
        "stress_management": ["stress management","pressure handling","work stress handling"],
        "teamwork": ["teamwork","team player","working in teams"],
        "time_management": ["time management","deadline management","schedule management"],
        "transparency": ["transparency","clear communication","openness"],
        "work_ethic": ["work ethic","strong work ethic","dedication"],
        "work_planning": ["work planning","task planning","execution planning"]
    },

    "collaboration_skills": {
        "team_collaboration": ["team collaboration","collaborative work","working in a team"],
        "cross_functional_coordination": ["cross functional coordination","cross team coordination","inter departmental coordination"],
        "conflict_resolution": ["conflict resolution","conflict management","dispute resolution"],
        "feedback_exchange": ["feedback giving","feedback receiving","giving and receiving feedback","constructive feedback"],
        "negotiation_skills": ["negotiation skills","professional negotiation","negotiation handling"],
        "stakeholder_alignment": ["stakeholder alignment","stakeholder coordination","stakeholder buy in"],
        "professional_empathy": ["empathy","professional empathy","empathy in workplace"],
        "cultural_awareness": ["cultural awareness","cultural sensitivity","workplace diversity awareness"],
        "remote_collaboration": ["remote collaboration","virtual collaboration","distributed team collaboration"],
        "mentoring_peer_support": ["mentoring","peer support","knowledge mentoring","peer mentoring"],
        "consensus_building": ["consensus building","decision consensus","group agreement"]
    },

    "ai_ml_aiml": {
        "aiml": ["aiml","ai ml","ai/ml","artificial intelligence and machine learning"],
        "artificial_intelligence": ["artificial intelligence","ai","ai systems"],
        "classification": ["classification","classification algorithms"],
        "clustering": ["clustering","clustering algorithms"],
        "computer_vision": ["computer vision","cv","image processing","visual recognition"],
        "data_preprocessing": ["data preprocessing","data cleaning","data preparation"],
        "deep_learning": ["deep learning","dl","deep neural networks"],
        "feature_engineering": ["feature engineering","feature extraction"],
        "generative_ai": ["generative ai","gen ai","genai","content generation ai"],
        "large_language_models": ["large language models","llm","llms"],
        "machine_learning": ["machine learning","ml","predictive modeling"],
        "model_deployment": ["model deployment","ml deployment","model serving"],
        "model_evaluation": ["model evaluation","model validation","performance evaluation"],
        "model_training": ["model training","training models","ml training"],
        "natural_language_processing": ["nlp","natural language processing","text processing"],
        "neural_networks": ["neural networks","ann","artificial neural networks"],
        "recommendation_systems": ["recommendation systems","recommender systems"],
        "reinforcement_learning": ["reinforcement learning","rl"],
        "supervised_learning": ["supervised learning","supervised ml"],
        "tensorflow": ["tensorflow","TensorFlow","tf"],
        "unsupervised_learning": ["unsupervised learning","unsupervised ml"],
        "pandas": ["pandas","Pandas","python pandas"],
        "numpy": ["numpy","NumPy","python numpy"],
        "pytorch": ["pytorch","PyTorch","torch"]
    },

    "data": {
        "big_data": ["big data","large scale data","big data processing"],
        "business_intelligence": ["business intelligence","bi","bi analytics"],
        "data_analysis": ["data analysis","data analytics","analytical data"],
        "data_cleaning": ["data cleaning","data cleansing","data preparation"],
        "data_collection": ["data collection","data gathering","data acquisition"],
        "data_engineering": ["data engineering","data engineer","data pipelines"],
        "data_governance": ["data governance","data management policies"],
        "data_modeling": ["data modeling","data models","schema design"],
        "data_science": ["data science","data scientist"],
        "data_visualization": ["data visualization","data visualisation","visual analytics"],
        "database_management": ["database management","db management"],
        "etl": ["etl","extract transform load","data integration"],
        "exploratory_data_analysis": ["eda","exploratory data analysis"],
        "feature_engineering": ["feature engineering","feature extraction"],
        "machine_learning_data": ["ml data","machine learning data","training data"],
        "numpy": ["numpy","NumPy","python numpy"],
        "pandas": ["pandas","Pandas","python pandas"],
        "powerbi": ["power bi","Power BI","microsoft power bi"],
        "sql": ["sql","SQL","structured query language"],
        "statistics": ["statistics","statistical analysis","descriptive statistics"],
        "tableau": ["tableau","Tableau","tableau dashboards"]
    },

    "project_management": {
        "agile": ["agile","agile methodology","agile practices"],
        "backlog_management": ["backlog management","product backlog"],
        "budget_tracking": ["budget tracking","cost tracking"],
        "delivery_management": ["delivery management","project delivery"],
        "estimation": ["estimation","effort estimation","time estimation"],
        "kanban": ["kanban","kanban board"],
        "milestone_tracking": ["milestone tracking","project milestones"],
        "project_planning": ["project planning","project scheduling"],
        "risk_management": ["risk management","project risk"],
        "scrum": ["scrum","scrum framework"],
        "sprint_planning": ["sprint planning","iteration planning"],
        "status_reporting": ["status reporting","project status updates"],
        "timeline_management": ["timeline management","schedule control"]
    },
    "customer_service": {
        "customer_support": ["customer support","client support"],
        "customer_satisfaction": ["customer satisfaction","csat"],
        "issue_tracking": ["issue tracking","ticket tracking"],
        "service_delivery": ["service delivery","service execution"],
        "sla_management": ["sla management","service level agreements"],
        "support_escalation": ["support escalation","issue escalation"],
        "technical_assistance": ["technical assistance","technical help"],
        "user_training": ["user training","end user training"]
    },


    "documentation_knowledge": {
        "api_documentation": ["api documentation","api docs"],
        "knowledge_base": ["knowledge base","kb articles"],
        "process_documentation": ["process documentation","workflow documentation"],
        "runbooks": ["runbooks","operational runbooks"],
        "standard_operating_procedures": ["sop","standard operating procedures"],
        "technical_writing": ["technical writing","technical documentation"],
        "user_guides": ["user guides","user manuals"]
    },

    "performance_optimization": {
        "bottleneck_analysis": ["bottleneck analysis","performance bottlenecks"],
        "capacity_planning": ["capacity planning","resource planning"],
        "load_testing": ["load testing","stress testing"],
        "performance_monitoring": ["performance monitoring","system performance"],
        "scalability": ["scalability","system scaling"],
        "throughput_optimization": ["throughput optimization","performance tuning"]
    },

    "compliance_privacy": {
        "audit_preparation": ["audit preparation","audit readiness"],
        "compliance_management": ["compliance management","regulatory compliance"],
        "data_privacy": ["data privacy","privacy protection"],
        "gdpr": ["gdpr","general data protection regulation"],
        "policy_enforcement": ["policy enforcement","security policies"],
        "risk_assessment": ["risk assessment","risk analysis"]
    },
    
    "training_enablement": {
        "onboarding": ["onboarding","employee onboarding"],
        "process_training": ["process training","workflow training"],
        "skill_development": ["skill development","upskilling"],
        "technical_training": ["technical training","technology training"],
        "workshop_facilitation": ["workshop facilitation","training workshops"]
    },

    "business_strategy": {
        "cost_optimization": ["cost optimization","cost reduction"],
        "kpi_tracking": ["kpi","key performance indicators"],
        "process_alignment": ["process alignment","business alignment"],
        "roi_analysis": ["roi analysis","return on investment"],
        "strategic_planning": ["strategic planning","business strategy"]
    },

    "personal_effectiveness": {
        "adaptability": ["adaptability","flexibility"],
        "focus_management": ["focus management","attention management"],
        "goal_setting": ["goal setting","objective setting"],
        "self_management": ["self management","self discipline"],
        "work_life_balance": ["work life balance","workload balance"]
    },

}